# vim: ft=python expandtab
from xml.etree.ElementTree import SubElement
from uuid import uuid4
from site_init import *
Import('env run_target')

icons_DATA = "x-office-presentation.png"
env.Alias('install', env.Install('$PREFIX/share/evince/icons/hicolor/32x32/mimetypes', icons_DATA))
run_dmimetypes = find_or_make_dir_with_parent(run_target, 'share/evince/icons/hicolor/i32x32/i32x32mimetypes', 'share/evince/icons/hicolor/32x32/mimetypes')
run_cmimetype = SubElement(run_dmimetypes, "Component", Id='c32x32mimetypes', Guid=str(uuid4()).upper())
FileElement(run_cmimetype, icons_DATA, 'share/evince/icons/hicolor/32x32/mimetypes', env, randomize_id = True)
