# vim: ft=python expandtab

Import('env')

icons_DATA = Split("\
	view-page-continuous.png	\
	view-page-facing.png")
env.Alias('install', env.Install('$PREFIX/share/evince/icons/hicolor/32x32/actions', icons_DATA))
