# vim: ft=python expandtab

Import('env')
'''
	-I$(top_srcdir)				\
	-I$(top_srcdir)/libdocument		\
	-DGNOMELOCALEDIR=\"$(datadir)/locale\"  \
	-DEVINCE_COMPILATION			\
	$(BACKEND_CFLAGS)			\
	$(POPPLER_CFLAGS)                       \
	$(WARN_CXXFLAGS)			\
	$(DISABLE_DEPRECATED)
'''
env_evgimpcellrenderertoggle = env.Clone(PDB='libevgimpcellrenderertoggle.pdb')
'''
env_evgimpcellrenderertoggle.Append(CPPDEFINES = [("GNOMELOCALEDIR", r'"\"' + env['PREFIX'].replace('\\', r'\\') + r'\\share\\locale\""'),
                                       ('LIBXML_SAX1_ENABLED'), #xmlParseMemory
                                       ("EVINCE_COMPILATION")])
'''
env_evgimpcellrenderertoggle.Append(CPPPATH=['#', '#libdocument', '../msvc'])

env_evgimpcellrenderertoggle.ParseConfig('pkg-config glib-2.0 --cflags --libs')
env_evgimpcellrenderertoggle.ParseConfig('pkg-config gio-2.0 --cflags --libs')
env_evgimpcellrenderertoggle.ParseConfig('pkg-config gtk+-2.0 --cflags --libs')
env_evgimpcellrenderertoggle.ParseConfig('pkg-config atk --cflags --libs')
env_evgimpcellrenderertoggle.ParseConfig('pkg-config cairo --cflags --libs')
env_evgimpcellrenderertoggle.ParseConfig('pkg-config pango --cflags --libs')
env_evgimpcellrenderertoggle.ParseConfig('pkg-config poppler-glib --cflags --libs')
env_evgimpcellrenderertoggle.ParseConfig('pkg-config libxml-2.0 --cflags --libs')

env_evgimpcellrenderertoggle['GLIB_GENMARSHAL_ARGV'] = [('prefix', '_gimp_widgets_marshal')]
env_evgimpcellrenderertoggle.MarshalGenerator(['gimpwidgetsmarshal.c', 'gimpwidgetsmarshal.h'], 'gimpwidgetsmarshal.list')
env_evgimpcellrenderertoggle.Depends(['gimpwidgetsmarshal.c', 'gimpwidgetsmarshal.h'], 'SConscript')
lib = env_evgimpcellrenderertoggle.StaticLibrary(['evgimpcellrenderertoggle.lib'], ["gimpcellrenderertoggle.c", "gimpwidgetsmarshal.c"])
env_evgimpcellrenderertoggle.Depends(lib, 'gimpwidgetsmarshal.h')
