# vim: ft=python expandtab

Import('env')

icons_DATA = Split("\
	view-page-continuous.png	\
	view-page-facing.png		\
	zoom.png                \
	zoom-fit-page.png		\
	zoom-fit-width.png")
env.Alias('install', env.Install('$PREFIX/share/evince/icons/hicolor/16x16/actions', icons_DATA))
