# vim: ft=python expandtab
from xml.etree.ElementTree import SubElement
from uuid import uuid4
from site_init import *
Import('env run_target')

icons_DATA = "evince.svg"
env.Alias('install', env.Install('$PREFIX/share/evince/icons/hicolor/scalable/apps', icons_DATA))
run_dapps = find_or_make_dir_with_parent(run_target, 'share/evince/icons/hicolor/scalable/scalableapps', 'share/evince/icons/hicolor/scalable/apps')
run_capp = SubElement(run_dapps, "Component", Id='cscalableapps', Guid=str(uuid4()).upper())
FileElement(run_capp, icons_DATA, 'share/evince/icons/hicolor/scalable/apps', env, randomize_id = True)
