# vim: ft=python expandtab

Import('env')

icons_DATA = Split("\
	eye.png				\
	object-rotate-left.png		\
	object-rotate-right.png		\
 	view-page-continuous.png	\
	view-page-continuous.png	\
	view-page-facing.png		\
	zoom.png                \
	zoom-fit-page.png		\
	zoom-fit-width.png")
env.Alias('install', env.Install('$PREFIX/share/evince/icons/hicolor/22x22/actions', icons_DATA))
