# vim: ft=python expandtab
from xml.etree.ElementTree import SubElement
from uuid import uuid4
from site_init import *
Import('env run_target')

icons_DATA = "evince.png"
env.Alias('install', env.Install('$PREFIX/share/evince/icons/hicolor/22x22/apps', icons_DATA))
run_dapps = find_or_make_dir_with_parent(run_target, 'share/evince/icons/hicolor/i22x22/i22x22apps', 'share/evince/icons/hicolor/22x22/apps')
run_capp = SubElement(run_dapps, "Component", Id='c22x22apps', Guid=str(uuid4()).upper())
FileElement(run_capp, icons_DATA, 'share/evince/icons/hicolor/22x22/apps', env, randomize_id = True)
