# vim: ft=python expandtab

Import('env')

icons_DATA = Split("\
	stock_filters-invert.png	\
	view-page-continuous.png	\
	view-page-facing.png		\
	zoom.png                \
	zoom-fit-page.png		\
	zoom-fit-width.png		\
	object-rotate-left.png		\
	object-rotate-right.png")
env.Alias('install', env.Install('$PREFIX/share/evince/icons/hicolor/24x24/actions', icons_DATA))
