# vim: ft=python expandtab

Import('env')
'''
	-I$(top_srcdir)				\
	-I$(top_srcdir)/libdocument		\
	-DGNOMELOCALEDIR=\"$(datadir)/locale\"  \
	-DEVINCE_COMPILATION			\
	$(BACKEND_CFLAGS)			\
	$(POPPLER_CFLAGS)                       \
	$(WARN_CXXFLAGS)			\
	$(DISABLE_DEPRECATED)
'''
env_evephyzoom = env.Clone(PDB='libevephyzoom.pdb')
'''
env_evephyzoom.Append(CPPDEFINES = [("GNOMELOCALEDIR", r'"\"' + env['PREFIX'].replace('\\', r'\\') + r'\\share\\locale\""'),
                                       ('LIBXML_SAX1_ENABLED'), #xmlParseMemory
                                       ("EVINCE_COMPILATION")])
'''
env_evephyzoom.Append(CPPPATH=['#'])

libephyzoom_la_SOURCES = Split("\
	ephy-zoom-action.c			\
	ephy-zoom-control.c			\
	ephy-zoom.c")

env_evephyzoom.ParseConfig('pkg-config glib-2.0 --cflags --libs')
env_evephyzoom.ParseConfig('pkg-config gio-2.0 --cflags --libs')
env_evephyzoom.ParseConfig('pkg-config gtk+-2.0 --cflags --libs')
env_evephyzoom.ParseConfig('pkg-config atk --cflags --libs')
env_evephyzoom.ParseConfig('pkg-config cairo --cflags --libs')
env_evephyzoom.ParseConfig('pkg-config pango --cflags --libs')
env_evephyzoom.ParseConfig('pkg-config poppler-glib --cflags --libs')
env_evephyzoom.ParseConfig('pkg-config libxml-2.0 --cflags --libs')

env_evephyzoom.StaticLibrary(['evephyzoom.lib'], libephyzoom_la_SOURCES)
