# vim: ft=python expandtab

Import('env')
'''
	-I$(top_srcdir)				\
	-I$(top_srcdir)/libdocument		\
	-DGNOMELOCALEDIR=\"$(datadir)/locale\"  \
	-DEVINCE_COMPILATION			\
	$(BACKEND_CFLAGS)			\
	$(POPPLER_CFLAGS)                       \
	$(WARN_CXXFLAGS)			\
	$(DISABLE_DEPRECATED)
'''
env_evsmclient = env.Clone(PDB='libevsmclient.pdb')
'''
env_evsmclient.Append(CPPDEFINES = [("GNOMELOCALEDIR", r'"\"' + env['PREFIX'].replace('\\', r'\\') + r'\\share\\locale\""'),
                                       ('LIBXML_SAX1_ENABLED'), #xmlParseMemory
                                       ("EVINCE_COMPILATION")])
'''
env_evsmclient.Append(CPPPATH=['#'])

env_evsmclient.ParseConfig('pkg-config glib-2.0 --cflags --libs')
env_evsmclient.ParseConfig('pkg-config gio-2.0 --cflags --libs')
env_evsmclient.ParseConfig('pkg-config gtk+-2.0 --cflags --libs')
env_evsmclient.ParseConfig('pkg-config atk --cflags --libs')
env_evsmclient.ParseConfig('pkg-config cairo --cflags --libs')
env_evsmclient.ParseConfig('pkg-config pango --cflags --libs')
env_evsmclient.ParseConfig('pkg-config poppler-glib --cflags --libs')
env_evsmclient.ParseConfig('pkg-config libxml-2.0 --cflags --libs')

env_evsmclient.StaticLibrary(['evsmclient.lib'], "eggsmclient-win32.c")
